name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx next build
        env:
          DATABASE_URL: "postgresql://localhost/ci_dummy"
          NEXTAUTH_SECRET: "ci_dummy_secret"
          NEXTAUTH_URL: "http://localhost:3000"